### ISSUE TITLE
Docker device mapping issue

### ISSUE THREAD

**Issue by plasticrake** [Koenkk/zigbee-herdsman#77]
I switched my `zigbee2mqtt` docker container from `latest` to `latest-dev`. On startup I was getting:

```
> zigbee2mqtt@1.6.0 start /app
> node index.js

zigbee2mqtt:error 2019-10-18T22:06:41: Error while starting zigbee-herdsman
zigbee2mqtt:error 2019-10-18T22:06:41: Failed to start zigbee
zigbee2mqtt:error 2019-10-18T22:06:41: Exiting...
zigbee2mqtt:error 2019-10-18T22:06:41: Error: Path '/dev/ttyACM0' does not exist
    at Object.<anonymous> (/app/node_modules/zigbee-herdsman/dist/adapter/serialPortUtils.js:34:19)
    at Generator.next (<anonymous>)
    at fulfilled (/app/node_modules/zigbee-herdsman/dist/adapter/serialPortUtils.js:5:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.6.0 start: `node index.js`
npm ERR! Exit status 1
```

I added this in `serialPortUtils.js` near the issue to get some debug info:

```js
        let devices = await SerialPort.list()
        console.warn(devices);
        const child_process = require('child_process');
        console.warn(child_process.execSync('ls /dev/tty*').toString('utf8'));
```

which output:

```js
[
  { manufacturer: undefined,
    serialNumber: undefined,
    pnpId: undefined,
    locationId: undefined,
    vendorId: undefined,
    productId: undefined,
    path: '/dev/ttyUSB0'
  },
  { manufacturer: undefined,
    serialNumber: undefined,
    pnpId: undefined,
    locationId: undefined,
    vendorId: undefined,
    productId: undefined,
    path: '/dev/ttyUSB1'
  },
  { manufacturer: undefined,
    serialNumber: undefined,
    pnpId: undefined,
    locationId: undefined,
    vendorId: undefined,
    productId: undefined,
    path: '/dev/ttyUSB2'
  },
  { manufacturer: undefined,
    serialNumber: undefined,
    pnpId: undefined,
    locationId: undefined,
    vendorId: undefined,
    productId: undefined,
    path: '/dev/ttyS0'
  },
  { manufacturer: undefined,
    serialNumber: undefined,
    pnpId: undefined,
    locationId: undefined,
    vendorId: undefined,
    productId: undefined,
    path: '/dev/ttyS1'
  },
  { manufacturer: undefined,
    serialNumber: undefined,
    pnpId: undefined,
    locationId: undefined,
    vendorId: undefined,
    productId: undefined,
    path: '/dev/ttyS2'
  },
  { manufacturer: undefined,
    serialNumber: undefined,
    pnpId: undefined,
    locationId: undefined,
    vendorId: undefined,
    productId: undefined,
    path: '/dev/ttyS3'
  }
]

/dev/tty
/dev/ttyACM0
```

Note that all the devices returned by `serialport.list()` don't appear to match what is in `/dev/`. I tried changing` /dev/ttyACM0` to `/dev/ttyUSB0` in both my docker config and z2m config and that fixed it! However this still seems like an issue that would affect other users not using one of these particular device names.

Probably related to serialport/node-serialport#1944

For reference my original docker-compose was:
```yaml
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:latest-dev
    depends_on:
    - mosquitto
    volumes:
    - ./zigbee2mqtt:/app/data
    devices:
    - /dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_0001-if00-port0:/dev/ttyACM0
    restart: unless-stopped
    network_mode: host
```
