### ISSUE TITLE
Network gets slow when using Ikea dimmer

### ISSUE THREAD

**Issue by h4nc** [Koenkk/zigbee-herdsman#88]
I updated to 1.7.0. and it worked until I tried to use my ikea dimmer. My system immediately got stuck. 
I tried several things (restarting, reinstalling) but only reflashing my stick made it work again. 

There is no error but when I'm using my ikea dimmer now the system gets extremely slow. Other devices won't work for some seconds. It feels like the dimmer sends to many messages and the system gets stuck because it has to worked itself though the messages. Inputs from other devices are handled after that. 

If I don't use the dimmer other devices work immediately. The device worked fine in former versions.

If someone can reproduce this users with ikea dimmers should be warned, because they might need to reflash, if the ikea dimmer does something nasty here.

**Comment by Koenkk** [comment]
I don't think messages of the dimmer are the issue, but that the automation made based on the dimmer are an issue. Due to https://github.com/Koenkk/zigbee-herdsman-converters/commit/ad29b2b6bcdb8ae561d21f2c8baf5c82fd681e51 it publishes more frequent -> if your automation responds to all of them using e.g. a dim command on a zigbee bulb, there will be a lot of commands.

**Comment by h4nc** [comment]
I see, thanks. Wasn't thinking of that. Was thinking that z2m must be the issue because this is what I changed.

So the issue that I had to reflash my device way most probably something different, I had an error there but did not save it (sry). Can't find it in the logs any more. 

This is my automation. Would it be better to use the sensor entity of the dimmer? I think this would probably change to often too? Or maybe adding some delay to the action at the end would help. But there is probably a more elegant way to do this. 

```
- alias:  ikea rotate - plus
  initial_state: 'on'
  trigger:
    platform: mqtt
    topic: 'zigbee2mqtt/Zigbee Dimmer WZ'
  condition:
    - condition: template
      value_template: "{{ trigger.payload_json.action in ['rotate_right', 'rotate_right_quick'] }}"
    - condition: state
      entity_id: light.wz
      state: 'on'             
  action:         
    - service: light.turn_on
      data_template:
        entity_id: light.wz
        brightness: "{{  states.light.wz.attributes.brightness | int + 25 }}"

```
